// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: getting-started.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Getting started\ndescription: Quick orientation for new contributors.\n---\n\n# Getting started {#getting-started}\n\nThree minutes to your first edit. Powered by [Dogsbay](https://github.com/dogsbay/dogsbay).\n\n## 1. Edit a page {#1-edit-a-page}\n\nOpen `content/index.md` in your editor and change something. Save — the dev server reloads automatically.\n\n## 2. Add a page {#2-add-a-page}\n\nCreate a new file like `content/about.md`:\n\n```md\n---\ntitle: About\n---\n\n# About\n\nWhatever you want to say here.\n```\n\nThen add it to `content/nav.yml` so it appears in the sidebar. Each entry is a single-key map — key = label, value = file path:\n\n```yaml\n- About: about.md\n```\n\nExternal URLs work the same way:\n\n```yaml\n- GitHub: https://github.com/your-org/your-repo\n```\n\n## 3. Group pages {#3-group-pages}\n\nTo create a section in the sidebar, give the entry a list of children instead of a single file:\n\n```yaml\n- Guides:\n    - Configuration: guides/configuration.md\n    - Deployment: guides/deployment.md\n```\n\nThe folder structure under `content/` doesn't have to match the nav — but it usually does, because it makes URLs predictable.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
