// Auto-generated by `dogsbay site build` — DO NOT EDIT.
// Tracks site.url + derived Astro base + build behaviour from
// dogsbay.config.yml. Edit dogsbay.config.yml and rebuild;
// edits to this file will be overwritten on the next build.
export const dogsbaySite = "https://dogsbay.ai";
export const dogsbayBase = "/dogsbay-xml-docs";
export const dogsbayInlineStylesheets = "auto";
export const dogsbayOutDir = "./dist/dogsbay-xml-docs";
