// AUTO-GENERATED by `dogsbay site build` — do not edit.
// Subpath-mount build steps. See project.ts (dogsbay-mount.mjs).
import { rmSync, existsSync, mkdirSync, renameSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const MOUNT_DIR = "dist/dogsbay-xml-docs";
// Resolve against THIS FILE, never process.cwd(). `pnpm build` runs
// with cwd set to the project, but this is an ordinary script sitting
// in the project root, and the natural CI/debug invocation
// `node path/to/site/dogsbay-mount.mjs clean` would otherwise
// recursively delete the CALLER's dist/.
const ROOT = dirname(fileURLToPath(import.meta.url));
const DIST = join(ROOT, "dist");
const mode = process.argv[2];

if (mode === "clean") {
  // Derived output only — astro build + pagefind regenerate all of it.
  rmSync(DIST, { recursive: true, force: true });
} else if (mode === "finalize") {
  // Cloudflare reads BOTH of these only from the root of the assets
  // directory, and Astro copies public/ into the mount dir — so on a
  // subpath mount they land at dist/<mount>/ and apply to nothing.
  for (const name of ["_headers", "_redirects"]) {
    const from = resolve(ROOT, `${MOUNT_DIR}/${name}`);
    if (!existsSync(from)) continue;
    const to = join(DIST, name);
    mkdirSync(dirname(to), { recursive: true });
    renameSync(from, to);
  }
} else {
  console.error("dogsbay-mount.mjs: expected `clean` or `finalize`");
  process.exit(1);
}
